// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBxDB6j2H5_zyFt30UteBxbnbmZJBSv-0',
    appId: '1:10849157104:web:3424ce183293a21c2be735',
    messagingSenderId: '10849157104',
    projectId: 'almokhtasar-5a325',
    authDomain: 'almokhtasar-5a325.firebaseapp.com',
    storageBucket: 'almokhtasar-5a325.appspot.com',
    measurementId: 'G-SDGZ3HF8CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfOUs-xC2zC8-mXculG4O7t1QlTN2yARE',
    appId: '1:10849157104:android:79e80eedbf58cb6c2be735',
    messagingSenderId: '10849157104',
    projectId: 'almokhtasar-5a325',
    storageBucket: 'almokhtasar-5a325.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCImpBlkNEzqxja7IxNOglbL0G9OQj_c7Q',
    appId: '1:10849157104:ios:615e2565aa6eded92be735',
    messagingSenderId: '10849157104',
    projectId: 'almokhtasar-5a325',
    storageBucket: 'almokhtasar-5a325.appspot.com',
    iosClientId: '10849157104-dbrsgupbdm16j0eqnsla3dkce5ti7hl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.elmokhtasar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCImpBlkNEzqxja7IxNOglbL0G9OQj_c7Q',
    appId: '1:10849157104:ios:615e2565aa6eded92be735',
    messagingSenderId: '10849157104',
    projectId: 'almokhtasar-5a325',
    storageBucket: 'almokhtasar-5a325.appspot.com',
    iosClientId: '10849157104-dbrsgupbdm16j0eqnsla3dkce5ti7hl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.elmokhtasar',
  );
}
